name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [ 'netcoreapp3.1']
    name: Dotnet Core ${{ matrix.framework }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.framework }}
      - run: dotnet build
      - run: dotnet test
